//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dziennik_ocenEntities : DbContext
    {
        public dziennik_ocenEntities()
            : base("name=dziennik_ocenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<kategorie_prowadzacych> kategorie_prowadzacych { get; set; }
        public DbSet<oceny_projekt> oceny_projekt { get; set; }
        public DbSet<oceny_przedmiot> oceny_przedmiot { get; set; }
        public DbSet<projekty> projekty { get; set; }
        public DbSet<prowadzacy> prowadzacy { get; set; }
        public DbSet<przedmioty> przedmioty { get; set; }
        public DbSet<studenci> studenci { get; set; }
        public DbSet<studenci_w_projektach> studenci_w_projektach { get; set; }
    }
}
