//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcen
{
    using System;
    using System.Collections.Generic;
    
    public partial class projekty
    {
        public int projekt_id { get; set; }
        public Nullable<int> prowadzacy_id { get; set; }
        public Nullable<int> przedmiot_id { get; set; }
        public string temat { get; set; }
        public int etap { get; set; }
    }
}
