//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcen
{
    using System;
    using System.Collections.Generic;
    
    public partial class prowadzacy
    {
        public int prowadzacy_id { get; set; }
        public Nullable<int> kategoria_id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string katedra { get; set; }
        public string email { get; set; }
        public string haslo { get; set; }
    }
}
