//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcen
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenci
    {
        public int student_id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string nr_indexu { get; set; }
        public string kierunek { get; set; }
        public string grupa { get; set; }
        public string email { get; set; }
        public string haslo { get; set; }
    }
}
