//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikOcen
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenci_w_projektach
    {
        public int student_id { get; set; }
        public int projekt_id { get; set; }
    }
}
